name: Deploy Image -- Latest

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: jreher
        password: ${{ secrets.dockerhub_key }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          jreher/latex-devcontainer:latest